/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTE25 (number 32), U2[6]/U10[6]/I2C0_SDA
  @{ */
#define BOARD_ACCEL_SDA_PERIPHERAL I2C0               /*!<@brief Device name: I2C0 */
#define BOARD_ACCEL_SDA_SIGNAL SDA                    /*!<@brief I2C0 signal: SDA */
#define BOARD_ACCEL_SDA_PORT PORTE                    /*!<@brief PORT device name: PORTE */
#define BOARD_ACCEL_SDA_PIN 25U                       /*!<@brief PORTE pin index: 25 */
#define BOARD_ACCEL_SDA_PIN_NAME I2C0_SDA             /*!<@brief Pin name */
#define BOARD_ACCEL_SDA_LABEL "U2[6]/U10[6]/I2C0_SDA" /*!<@brief Label */
#define BOARD_ACCEL_SDA_NAME "ACCEL_SDA"              /*!<@brief Identifier name */
                                                      /* @} */

/*! @name PORTE24 (number 31), U2[7]/U10[4]/I2C0_SDA
  @{ */
#define BOARD_ACCEL_SCL_PERIPHERAL I2C0               /*!<@brief Device name: I2C0 */
#define BOARD_ACCEL_SCL_SIGNAL SCL                    /*!<@brief I2C0 signal: SCL */
#define BOARD_ACCEL_SCL_PORT PORTE                    /*!<@brief PORT device name: PORTE */
#define BOARD_ACCEL_SCL_PIN 24U                       /*!<@brief PORTE pin index: 24 */
#define BOARD_ACCEL_SCL_PIN_NAME I2C0_SCL             /*!<@brief Pin name */
#define BOARD_ACCEL_SCL_LABEL "U2[7]/U10[4]/I2C0_SDA" /*!<@brief Label */
#define BOARD_ACCEL_SCL_NAME "ACCEL_SCL"              /*!<@brief Identifier name */
                                                      /* @} */

/*! @name PORTC5 (number 81), U10[11]/INT1_ACCEL
  @{ */
#define BOARD_ACCEL_INT1_PERIPHERAL GPIOC                  /*!<@brief Device name: GPIOC */
#define BOARD_ACCEL_INT1_SIGNAL GPIO                       /*!<@brief GPIOC signal: GPIO */
#define BOARD_ACCEL_INT1_GPIO GPIOC                        /*!<@brief GPIO device name: GPIOC */
#define BOARD_ACCEL_INT1_GPIO_PIN 5U                       /*!<@brief PORTC pin index: 5 */
#define BOARD_ACCEL_INT1_PORT PORTC                        /*!<@brief PORT device name: PORTC */
#define BOARD_ACCEL_INT1_PIN 5U                            /*!<@brief PORTC pin index: 5 */
#define BOARD_ACCEL_INT1_CHANNEL 5                         /*!<@brief GPIOC GPIO channel: 5 */
#define BOARD_ACCEL_INT1_PIN_NAME PTC5                     /*!<@brief Pin name */
#define BOARD_ACCEL_INT1_LABEL "U10[11]/INT1_ACCEL"        /*!<@brief Label */
#define BOARD_ACCEL_INT1_NAME "ACCEL_INT1"                 /*!<@brief Identifier name */
#define BOARD_ACCEL_INT1_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                           /* @} */

/*! @name PORTD1 (number 94), U2[9]/U10[9]/INT2_ACCEL
  @{ */
#define BOARD_ACCEL_INT2_PERIPHERAL GPIOD                  /*!<@brief Device name: GPIOD */
#define BOARD_ACCEL_INT2_SIGNAL GPIO                       /*!<@brief GPIOD signal: GPIO */
#define BOARD_ACCEL_INT2_GPIO GPIOD                        /*!<@brief GPIO device name: GPIOD */
#define BOARD_ACCEL_INT2_GPIO_PIN 1U                       /*!<@brief PORTD pin index: 1 */
#define BOARD_ACCEL_INT2_PORT PORTD                        /*!<@brief PORT device name: PORTD */
#define BOARD_ACCEL_INT2_PIN 1U                            /*!<@brief PORTD pin index: 1 */
#define BOARD_ACCEL_INT2_CHANNEL 1                         /*!<@brief GPIOD GPIO channel: 1 */
#define BOARD_ACCEL_INT2_PIN_NAME PTD1                     /*!<@brief Pin name */
#define BOARD_ACCEL_INT2_LABEL "U2[9]/U10[9]/INT2_ACCEL"   /*!<@brief Label */
#define BOARD_ACCEL_INT2_NAME "ACCEL_INT2"                 /*!<@brief Identifier name */
#define BOARD_ACCEL_INT2_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitACCEL(void);

#define SOPT5_UART0ODE_DISABLED 0x00u  /*!<@brief UART0 Open Drain Enable: Open drain is disabled on UART0. */
#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 Receive Data Source Select: UART_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 Transmit Data Source Select: UART0_TX pin */

/*! @name PORTA2 (number 36), J1[4]/D1/UART1_TX_TGTMCU
  @{ */
#define BOARD_DEBUG_UART_TX_PERIPHERAL UART0                   /*!<@brief Device name: UART0 */
#define BOARD_DEBUG_UART_TX_SIGNAL TX                          /*!<@brief UART0 signal: TX */
#define BOARD_DEBUG_UART_TX_PORT PORTA                         /*!<@brief PORT device name: PORTA */
#define BOARD_DEBUG_UART_TX_PIN 2U                             /*!<@brief PORTA pin index: 2 */
#define BOARD_DEBUG_UART_TX_PIN_NAME UART0_TX                  /*!<@brief Pin name */
#define BOARD_DEBUG_UART_TX_LABEL "J1[4]/D1/UART1_TX_TGTMCU"   /*!<@brief Label */
#define BOARD_DEBUG_UART_TX_NAME "DEBUG_UART_TX"               /*!<@brief Identifier name */
#define BOARD_DEBUG_UART_TX_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                               /* @} */

/*! @name PORTA1 (number 35), J1[2]/D0/UART1_RX_TGTMCU
  @{ */
#define BOARD_DEBUG_UART_RX_PERIPHERAL UART0                 /*!<@brief Device name: UART0 */
#define BOARD_DEBUG_UART_RX_SIGNAL RX                        /*!<@brief UART0 signal: RX */
#define BOARD_DEBUG_UART_RX_PORT PORTA                       /*!<@brief PORT device name: PORTA */
#define BOARD_DEBUG_UART_RX_PIN 1U                           /*!<@brief PORTA pin index: 1 */
#define BOARD_DEBUG_UART_RX_PIN_NAME UART0_RX                /*!<@brief Pin name */
#define BOARD_DEBUG_UART_RX_LABEL "J1[2]/D0/UART1_RX_TGTMCU" /*!<@brief Label */
#define BOARD_DEBUG_UART_RX_NAME "DEBUG_UART_RX"             /*!<@brief Identifier name */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UART(void);

/*! @name PORTC3 (number 73), SW1
  @{ */
#define BOARD_SW1_PERIPHERAL GPIOC                  /*!<@brief Device name: GPIOC */
#define BOARD_SW1_SIGNAL GPIO                       /*!<@brief GPIOC signal: GPIO */
#define BOARD_SW1_GPIO GPIOC                        /*!<@brief GPIO device name: GPIOC */
#define BOARD_SW1_GPIO_PIN 3U                       /*!<@brief PORTC pin index: 3 */
#define BOARD_SW1_PORT PORTC                        /*!<@brief PORT device name: PORTC */
#define BOARD_SW1_PIN 3U                            /*!<@brief PORTC pin index: 3 */
#define BOARD_SW1_CHANNEL 3                         /*!<@brief GPIOC GPIO channel: 3 */
#define BOARD_SW1_PIN_NAME PTC3                     /*!<@brief Pin name */
#define BOARD_SW1_LABEL "SW1"                       /*!<@brief Label */
#define BOARD_SW1_NAME "SW1"                        /*!<@brief Identifier name */
#define BOARD_SW1_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                    /* @} */

/*! @name PORTC12 (number 88), SW3
  @{ */
#define BOARD_SW3_PERIPHERAL GPIOC                  /*!<@brief Device name: GPIOC */
#define BOARD_SW3_SIGNAL GPIO                       /*!<@brief GPIOC signal: GPIO */
#define BOARD_SW3_GPIO GPIOC                        /*!<@brief GPIO device name: GPIOC */
#define BOARD_SW3_GPIO_PIN 12U                      /*!<@brief PORTC pin index: 12 */
#define BOARD_SW3_PORT PORTC                        /*!<@brief PORT device name: PORTC */
#define BOARD_SW3_PIN 12U                           /*!<@brief PORTC pin index: 12 */
#define BOARD_SW3_CHANNEL 12                        /*!<@brief GPIOC GPIO channel: 12 */
#define BOARD_SW3_PIN_NAME PTC12                    /*!<@brief Pin name */
#define BOARD_SW3_LABEL "SW3"                       /*!<@brief Label */
#define BOARD_SW3_NAME "SW3"                        /*!<@brief Identifier name */
#define BOARD_SW3_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitButtons(void);

/*! @name PORTE29 (number 26), LED_RED
  @{ */
#define BOARD_LED_RED_PERIPHERAL GPIOE                   /*!<@brief Device name: GPIOE */
#define BOARD_LED_RED_SIGNAL GPIO                        /*!<@brief GPIOE signal: GPIO */
#define BOARD_LED_RED_GPIO GPIOE                         /*!<@brief GPIO device name: GPIOE */
#define BOARD_LED_RED_GPIO_PIN 29U                       /*!<@brief PORTE pin index: 29 */
#define BOARD_LED_RED_PORT PORTE                         /*!<@brief PORT device name: PORTE */
#define BOARD_LED_RED_PIN 29U                            /*!<@brief PORTE pin index: 29 */
#define BOARD_LED_RED_CHANNEL 29                         /*!<@brief GPIOE GPIO channel: 29 */
#define BOARD_LED_RED_PIN_NAME PTE29                     /*!<@brief Pin name */
#define BOARD_LED_RED_LABEL "LED_RED"                    /*!<@brief Label */
#define BOARD_LED_RED_NAME "LED_RED"                     /*!<@brief Identifier name */
#define BOARD_LED_RED_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                         /* @} */

/*! @name PORTD5 (number 98), J2[12]/D13/LED_GREEN
  @{ */
#define BOARD_LED_GREEN_PERIPHERAL GPIOD                   /*!<@brief Device name: GPIOD */
#define BOARD_LED_GREEN_SIGNAL GPIO                        /*!<@brief GPIOD signal: GPIO */
#define BOARD_LED_GREEN_GPIO GPIOD                         /*!<@brief GPIO device name: GPIOD */
#define BOARD_LED_GREEN_GPIO_PIN 5U                        /*!<@brief PORTD pin index: 5 */
#define BOARD_LED_GREEN_PORT PORTD                         /*!<@brief PORT device name: PORTD */
#define BOARD_LED_GREEN_PIN 5U                             /*!<@brief PORTD pin index: 5 */
#define BOARD_LED_GREEN_CHANNEL 5                          /*!<@brief GPIOD GPIO channel: 5 */
#define BOARD_LED_GREEN_PIN_NAME PTD5                      /*!<@brief Pin name */
#define BOARD_LED_GREEN_LABEL "J2[12]/D13/LED_GREEN"       /*!<@brief Label */
#define BOARD_LED_GREEN_NAME "LED_GREEN"                   /*!<@brief Identifier name */
#define BOARD_LED_GREEN_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDs(void);

/*! @name PORTB16 (number 62), E1/TSI_ELECTRODE1
  @{ */
#define BOARD_TSI_ELECTRODE_1_PERIPHERAL TSI0           /*!<@brief Device name: TSI0 */
#define BOARD_TSI_ELECTRODE_1_SIGNAL CH                 /*!<@brief TSI0 signal: CH */
#define BOARD_TSI_ELECTRODE_1_PORT PORTB                /*!<@brief PORT device name: PORTB */
#define BOARD_TSI_ELECTRODE_1_PIN 16U                   /*!<@brief PORTB pin index: 16 */
#define BOARD_TSI_ELECTRODE_1_CHANNEL 9                 /*!<@brief TSI0 channel: 9 */
#define BOARD_TSI_ELECTRODE_1_PIN_NAME TSI0_CH9         /*!<@brief Pin name */
#define BOARD_TSI_ELECTRODE_1_LABEL "E1/TSI_ELECTRODE1" /*!<@brief Label */
#define BOARD_TSI_ELECTRODE_1_NAME "TSI_ELECTRODE_1"    /*!<@brief Identifier name */
                                                        /* @} */

/*! @name PORTB17 (number 63), E1/TSI_ELECTRODE2
  @{ */
#define BOARD_TSI_ELECTRODE_2_PERIPHERAL TSI0           /*!<@brief Device name: TSI0 */
#define BOARD_TSI_ELECTRODE_2_SIGNAL CH                 /*!<@brief TSI0 signal: CH */
#define BOARD_TSI_ELECTRODE_2_PORT PORTB                /*!<@brief PORT device name: PORTB */
#define BOARD_TSI_ELECTRODE_2_PIN 17U                   /*!<@brief PORTB pin index: 17 */
#define BOARD_TSI_ELECTRODE_2_CHANNEL 10                /*!<@brief TSI0 channel: 10 */
#define BOARD_TSI_ELECTRODE_2_PIN_NAME TSI0_CH10        /*!<@brief Pin name */
#define BOARD_TSI_ELECTRODE_2_LABEL "E1/TSI_ELECTRODE2" /*!<@brief Label */
#define BOARD_TSI_ELECTRODE_2_NAME "TSI_ELECTRODE_2"    /*!<@brief Identifier name */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitTouch(void);

/*! @name USB0_DM (number 11), J10[2]/USB_DM
  @{ */
#define BOARD_USB_DM_PERIPHERAL USB0       /*!<@brief Device name: USB0 */
#define BOARD_USB_DM_SIGNAL DM             /*!<@brief USB0 signal: DM */
#define BOARD_USB_DM_PIN_NAME USB0_DM      /*!<@brief Pin name */
#define BOARD_USB_DM_LABEL "J10[2]/USB_DM" /*!<@brief Label */
#define BOARD_USB_DM_NAME "USB_DM"         /*!<@brief Identifier name */
                                           /* @} */

/*! @name USB0_DP (number 10), J10[3]/USB_DP
  @{ */
#define BOARD_USB_DP_PERIPHERAL USB0       /*!<@brief Device name: USB0 */
#define BOARD_USB_DP_SIGNAL DP             /*!<@brief USB0 signal: DP */
#define BOARD_USB_DP_PIN_NAME USB0_DP      /*!<@brief Pin name */
#define BOARD_USB_DP_LABEL "J10[3]/USB_DP" /*!<@brief Label */
#define BOARD_USB_DP_NAME "USB_DP"         /*!<@brief Identifier name */
                                           /* @} */

/*! @name VREGIN (number 13), J7[2]/KL46Z_REGIN
  @{ */
#define BOARD_USB_VREGIN_PERIPHERAL USB0           /*!<@brief Device name: USB0 */
#define BOARD_USB_VREGIN_SIGNAL VREGIN             /*!<@brief USB0 signal: VREGIN */
#define BOARD_USB_VREGIN_PIN_NAME VREGIN           /*!<@brief Pin name */
#define BOARD_USB_VREGIN_LABEL "J7[2]/KL46Z_REGIN" /*!<@brief Label */
#define BOARD_USB_VREGIN_NAME "USB_VREGIN"         /*!<@brief Identifier name */
                                                   /* @} */

/*! @name VOUT33 (number 12), C11/VOUT33
  @{ */
#define BOARD_VOUT33_PERIPHERAL USB0    /*!<@brief Device name: USB0 */
#define BOARD_VOUT33_SIGNAL VOUT33      /*!<@brief USB0 signal: VOUT33 */
#define BOARD_VOUT33_PIN_NAME VOUT33    /*!<@brief Pin name */
#define BOARD_VOUT33_LABEL "C11/VOUT33" /*!<@brief Label */
#define BOARD_VOUT33_NAME "VOUT33"      /*!<@brief Identifier name */
                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSB(void);

/*! @name PORTB11 (number 61), DS1[12]/LCD-12
  @{ */
#define BOARD_LCD_12_PERIPHERAL LCD         /*!<@brief Device name: LCD */
#define BOARD_LCD_12_SIGNAL P               /*!<@brief LCD signal: P */
#define BOARD_LCD_12_PORT PORTB             /*!<@brief PORT device name: PORTB */
#define BOARD_LCD_12_PIN 11U                /*!<@brief PORTB pin index: 11 */
#define BOARD_LCD_12_CHANNEL 11             /*!<@brief LCD P channel: 11 */
#define BOARD_LCD_12_PIN_NAME LCD_P11       /*!<@brief Pin name */
#define BOARD_LCD_12_LABEL "DS1[12]/LCD-12" /*!<@brief Label */
#define BOARD_LCD_12_NAME "LCD_12"          /*!<@brief Identifier name */
                                            /* @} */

/*! @name PORTB10 (number 60), DS1[11]/LCD-11
  @{ */
#define BOARD_LCD_11_PERIPHERAL LCD         /*!<@brief Device name: LCD */
#define BOARD_LCD_11_SIGNAL P               /*!<@brief LCD signal: P */
#define BOARD_LCD_11_PORT PORTB             /*!<@brief PORT device name: PORTB */
#define BOARD_LCD_11_PIN 10U                /*!<@brief PORTB pin index: 10 */
#define BOARD_LCD_11_CHANNEL 10             /*!<@brief LCD P channel: 10 */
#define BOARD_LCD_11_PIN_NAME LCD_P10       /*!<@brief Pin name */
#define BOARD_LCD_11_LABEL "DS1[11]/LCD-11" /*!<@brief Label */
#define BOARD_LCD_11_NAME "LCD_11"          /*!<@brief Identifier name */
                                            /* @} */

/*! @name PORTC18 (number 92), DS1[10]/LCD-10
  @{ */
#define BOARD_LCD_10_PERIPHERAL LCD         /*!<@brief Device name: LCD */
#define BOARD_LCD_10_SIGNAL P               /*!<@brief LCD signal: P */
#define BOARD_LCD_10_PORT PORTC             /*!<@brief PORT device name: PORTC */
#define BOARD_LCD_10_PIN 18U                /*!<@brief PORTC pin index: 18 */
#define BOARD_LCD_10_CHANNEL 38             /*!<@brief LCD P channel: 38 */
#define BOARD_LCD_10_PIN_NAME LCD_P38       /*!<@brief Pin name */
#define BOARD_LCD_10_LABEL "DS1[10]/LCD-10" /*!<@brief Label */
#define BOARD_LCD_10_NAME "LCD_10"          /*!<@brief Identifier name */
                                            /* @} */

/*! @name PORTE5 (number 6), DS1[9]/LCD-09
  @{ */
#define BOARD_LCD_09_PERIPHERAL LCD        /*!<@brief Device name: LCD */
#define BOARD_LCD_09_SIGNAL P              /*!<@brief LCD signal: P */
#define BOARD_LCD_09_PORT PORTE            /*!<@brief PORT device name: PORTE */
#define BOARD_LCD_09_PIN 5U                /*!<@brief PORTE pin index: 5 */
#define BOARD_LCD_09_CHANNEL 53            /*!<@brief LCD P channel: 53 */
#define BOARD_LCD_09_PIN_NAME LCD_P53      /*!<@brief Pin name */
#define BOARD_LCD_09_LABEL "DS1[9]/LCD-09" /*!<@brief Label */
#define BOARD_LCD_09_NAME "LCD_09"         /*!<@brief Identifier name */
                                           /* @} */

/*! @name PORTB8 (number 58), DS1[8]/LCD-08
  @{ */
#define BOARD_LCD_08_PERIPHERAL LCD        /*!<@brief Device name: LCD */
#define BOARD_LCD_08_SIGNAL P              /*!<@brief LCD signal: P */
#define BOARD_LCD_08_PORT PORTB            /*!<@brief PORT device name: PORTB */
#define BOARD_LCD_08_PIN 8U                /*!<@brief PORTB pin index: 8 */
#define BOARD_LCD_08_CHANNEL 8             /*!<@brief LCD P channel: 8 */
#define BOARD_LCD_08_PIN_NAME LCD_P8       /*!<@brief Pin name */
#define BOARD_LCD_08_LABEL "DS1[8]/LCD-08" /*!<@brief Label */
#define BOARD_LCD_08_NAME "LCD_08"         /*!<@brief Identifier name */
                                           /* @} */

/*! @name PORTB7 (number 57), DS1[7]/LCD-07
  @{ */
#define BOARD_LCD_07_PERIPHERAL LCD        /*!<@brief Device name: LCD */
#define BOARD_LCD_07_SIGNAL P              /*!<@brief LCD signal: P */
#define BOARD_LCD_07_PORT PORTB            /*!<@brief PORT device name: PORTB */
#define BOARD_LCD_07_PIN 7U                /*!<@brief PORTB pin index: 7 */
#define BOARD_LCD_07_CHANNEL 7             /*!<@brief LCD P channel: 7 */
#define BOARD_LCD_07_PIN_NAME LCD_P7       /*!<@brief Pin name */
#define BOARD_LCD_07_LABEL "DS1[7]/LCD-07" /*!<@brief Label */
#define BOARD_LCD_07_NAME "LCD_07"         /*!<@brief Identifier name */
                                           /* @} */

/*! @name PORTB21 (number 67), DS1[6]/LCD-06
  @{ */
#define BOARD_LCD_06_PERIPHERAL LCD        /*!<@brief Device name: LCD */
#define BOARD_LCD_06_SIGNAL P              /*!<@brief LCD signal: P */
#define BOARD_LCD_06_PORT PORTB            /*!<@brief PORT device name: PORTB */
#define BOARD_LCD_06_PIN 21U               /*!<@brief PORTB pin index: 21 */
#define BOARD_LCD_06_CHANNEL 17            /*!<@brief LCD P channel: 17 */
#define BOARD_LCD_06_PIN_NAME LCD_P17      /*!<@brief Pin name */
#define BOARD_LCD_06_LABEL "DS1[6]/LCD-06" /*!<@brief Label */
#define BOARD_LCD_06_NAME "LCD_06"         /*!<@brief Identifier name */
                                           /* @} */

/*! @name PORTC17 (number 91), DS1[5]/LCD-05
  @{ */
#define BOARD_LCD_05_PERIPHERAL LCD        /*!<@brief Device name: LCD */
#define BOARD_LCD_05_SIGNAL P              /*!<@brief LCD signal: P */
#define BOARD_LCD_05_PORT PORTC            /*!<@brief PORT device name: PORTC */
#define BOARD_LCD_05_PIN 17U               /*!<@brief PORTC pin index: 17 */
#define BOARD_LCD_05_CHANNEL 37            /*!<@brief LCD P channel: 37 */
#define BOARD_LCD_05_PIN_NAME LCD_P37      /*!<@brief Pin name */
#define BOARD_LCD_05_LABEL "DS1[5]/LCD-05" /*!<@brief Label */
#define BOARD_LCD_05_NAME "LCD_05"         /*!<@brief Identifier name */
                                           /* @} */

/*! @name PORTB22 (number 68), DS1[4]/LCD-04
  @{ */
#define BOARD_LCD_04_PERIPHERAL LCD        /*!<@brief Device name: LCD */
#define BOARD_LCD_04_SIGNAL P              /*!<@brief LCD signal: P */
#define BOARD_LCD_04_PORT PORTB            /*!<@brief PORT device name: PORTB */
#define BOARD_LCD_04_PIN 22U               /*!<@brief PORTB pin index: 22 */
#define BOARD_LCD_04_CHANNEL 18            /*!<@brief LCD P channel: 18 */
#define BOARD_LCD_04_PIN_NAME LCD_P18      /*!<@brief Pin name */
#define BOARD_LCD_04_LABEL "DS1[4]/LCD-04" /*!<@brief Label */
#define BOARD_LCD_04_NAME "LCD_04"         /*!<@brief Identifier name */
                                           /* @} */

/*! @name PORTB23 (number 69), DS1[3]/LCD-03
  @{ */
#define BOARD_LCD_03_PERIPHERAL LCD        /*!<@brief Device name: LCD */
#define BOARD_LCD_03_SIGNAL P              /*!<@brief LCD signal: P */
#define BOARD_LCD_03_PORT PORTB            /*!<@brief PORT device name: PORTB */
#define BOARD_LCD_03_PIN 23U               /*!<@brief PORTB pin index: 23 */
#define BOARD_LCD_03_CHANNEL 19            /*!<@brief LCD P channel: 19 */
#define BOARD_LCD_03_PIN_NAME LCD_P19      /*!<@brief Pin name */
#define BOARD_LCD_03_LABEL "DS1[3]/LCD-03" /*!<@brief Label */
#define BOARD_LCD_03_NAME "LCD_03"         /*!<@brief Identifier name */
                                           /* @} */

/*! @name PORTE4 (number 5), DS1[2]/LCD-02
  @{ */
#define BOARD_LCD_02_PERIPHERAL LCD        /*!<@brief Device name: LCD */
#define BOARD_LCD_02_SIGNAL P              /*!<@brief LCD signal: P */
#define BOARD_LCD_02_PORT PORTE            /*!<@brief PORT device name: PORTE */
#define BOARD_LCD_02_PIN 4U                /*!<@brief PORTE pin index: 4 */
#define BOARD_LCD_02_CHANNEL 52            /*!<@brief LCD P channel: 52 */
#define BOARD_LCD_02_PIN_NAME LCD_P52      /*!<@brief Pin name */
#define BOARD_LCD_02_LABEL "DS1[2]/LCD-02" /*!<@brief Label */
#define BOARD_LCD_02_NAME "LCD_02"         /*!<@brief Identifier name */
                                           /* @} */

/*! @name PORTD0 (number 93), DS1[1]/LCD-01
  @{ */
#define BOARD_LCD_01_PERIPHERAL LCD        /*!<@brief Device name: LCD */
#define BOARD_LCD_01_SIGNAL P              /*!<@brief LCD signal: P */
#define BOARD_LCD_01_PORT PORTD            /*!<@brief PORT device name: PORTD */
#define BOARD_LCD_01_PIN 0U                /*!<@brief PORTD pin index: 0 */
#define BOARD_LCD_01_CHANNEL 40            /*!<@brief LCD P channel: 40 */
#define BOARD_LCD_01_PIN_NAME LCD_P40      /*!<@brief Pin name */
#define BOARD_LCD_01_LABEL "DS1[1]/LCD-01" /*!<@brief Label */
#define BOARD_LCD_01_NAME "LCD_01"         /*!<@brief Identifier name */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSegment_LCD(void);

/*! @name PORTA19 (number 51), Y1[3]/XTAL_8MHZ
  @{ */
#define BOARD_XTAL0_PERIPHERAL OSC0         /*!<@brief Device name: OSC0 */
#define BOARD_XTAL0_SIGNAL XTAL0            /*!<@brief OSC0 signal: XTAL0 */
#define BOARD_XTAL0_PORT PORTA              /*!<@brief PORT device name: PORTA */
#define BOARD_XTAL0_PIN 19U                 /*!<@brief PORTA pin index: 19 */
#define BOARD_XTAL0_PIN_NAME XTAL0          /*!<@brief Pin name */
#define BOARD_XTAL0_LABEL "Y1[3]/XTAL_8MHZ" /*!<@brief Label */
#define BOARD_XTAL0_NAME "XTAL0"            /*!<@brief Identifier name */
                                            /* @} */

/*! @name PORTA18 (number 50), Y1[1]/EXTAL_8MHZ
  @{ */
#define BOARD_EXTAL0_PERIPHERAL OSC0          /*!<@brief Device name: OSC0 */
#define BOARD_EXTAL0_SIGNAL EXTAL0            /*!<@brief OSC0 signal: EXTAL0 */
#define BOARD_EXTAL0_PORT PORTA               /*!<@brief PORT device name: PORTA */
#define BOARD_EXTAL0_PIN 18U                  /*!<@brief PORTA pin index: 18 */
#define BOARD_EXTAL0_PIN_NAME EXTAL0          /*!<@brief Pin name */
#define BOARD_EXTAL0_LABEL "Y1[1]/EXTAL_8MHZ" /*!<@brief Label */
#define BOARD_EXTAL0_NAME "EXTAL0"            /*!<@brief Identifier name */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOSC(void);

/*! @name PORTE25 (number 32), U2[6]/U10[6]/I2C0_SDA
  @{ */
#define BOARD_MAG_SDA_PERIPHERAL I2C0               /*!<@brief Device name: I2C0 */
#define BOARD_MAG_SDA_SIGNAL SDA                    /*!<@brief I2C0 signal: SDA */
#define BOARD_MAG_SDA_PORT PORTE                    /*!<@brief PORT device name: PORTE */
#define BOARD_MAG_SDA_PIN 25U                       /*!<@brief PORTE pin index: 25 */
#define BOARD_MAG_SDA_PIN_NAME I2C0_SDA             /*!<@brief Pin name */
#define BOARD_MAG_SDA_LABEL "U2[6]/U10[6]/I2C0_SDA" /*!<@brief Label */
#define BOARD_MAG_SDA_NAME "MAG_SDA"                /*!<@brief Identifier name */
                                                    /* @} */

/*! @name PORTE24 (number 31), U2[7]/U10[4]/I2C0_SDA
  @{ */
#define BOARD_MAG_SCL_PERIPHERAL I2C0               /*!<@brief Device name: I2C0 */
#define BOARD_MAG_SCL_SIGNAL SCL                    /*!<@brief I2C0 signal: SCL */
#define BOARD_MAG_SCL_PORT PORTE                    /*!<@brief PORT device name: PORTE */
#define BOARD_MAG_SCL_PIN 24U                       /*!<@brief PORTE pin index: 24 */
#define BOARD_MAG_SCL_PIN_NAME I2C0_SCL             /*!<@brief Pin name */
#define BOARD_MAG_SCL_LABEL "U2[7]/U10[4]/I2C0_SDA" /*!<@brief Label */
#define BOARD_MAG_SCL_NAME "MAG_SCL"                /*!<@brief Identifier name */
                                                    /* @} */

/*! @name PORTD1 (number 94), U2[9]/U10[9]/INT2_ACCEL
  @{ */
#define BOARD_MAG_INT2_PERIPHERAL GPIOD                  /*!<@brief Device name: GPIOD */
#define BOARD_MAG_INT2_SIGNAL GPIO                       /*!<@brief GPIOD signal: GPIO */
#define BOARD_MAG_INT2_GPIO GPIOD                        /*!<@brief GPIO device name: GPIOD */
#define BOARD_MAG_INT2_GPIO_PIN 1U                       /*!<@brief PORTD pin index: 1 */
#define BOARD_MAG_INT2_PORT PORTD                        /*!<@brief PORT device name: PORTD */
#define BOARD_MAG_INT2_PIN 1U                            /*!<@brief PORTD pin index: 1 */
#define BOARD_MAG_INT2_CHANNEL 1                         /*!<@brief GPIOD GPIO channel: 1 */
#define BOARD_MAG_INT2_PIN_NAME PTD1                     /*!<@brief Pin name */
#define BOARD_MAG_INT2_LABEL "U2[9]/U10[9]/INT2_ACCEL"   /*!<@brief Label */
#define BOARD_MAG_INT2_NAME "MAG_INT2"                   /*!<@brief Identifier name */
#define BOARD_MAG_INT2_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMAG(void);

/*! @name PORTC8 (number 84), J1[14]/D6
  @{ */
#define BOARD_INITSNES_SNES_CLK_PERIPHERAL GPIOC                   /*!<@brief Device name: GPIOC */
#define BOARD_INITSNES_SNES_CLK_SIGNAL GPIO                        /*!<@brief GPIOC signal: GPIO */
#define BOARD_INITSNES_SNES_CLK_GPIO GPIOC                         /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITSNES_SNES_CLK_GPIO_PIN 8U                        /*!<@brief PORTC pin index: 8 */
#define BOARD_INITSNES_SNES_CLK_PORT PORTC                         /*!<@brief PORT device name: PORTC */
#define BOARD_INITSNES_SNES_CLK_PIN 8U                             /*!<@brief PORTC pin index: 8 */
#define BOARD_INITSNES_SNES_CLK_CHANNEL 8                          /*!<@brief GPIOC GPIO channel: 8 */
#define BOARD_INITSNES_SNES_CLK_PIN_NAME PTC8                      /*!<@brief Pin name */
#define BOARD_INITSNES_SNES_CLK_LABEL "J1[14]/D6"                  /*!<@brief Label */
#define BOARD_INITSNES_SNES_CLK_NAME "SNES_CLK"                    /*!<@brief Identifier name */
#define BOARD_INITSNES_SNES_CLK_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                                   /* @} */

/*! @name PORTC9 (number 85), J1[16]/D7
  @{ */
#define BOARD_INITSNES_SNES_LAT_PERIPHERAL GPIOC                   /*!<@brief Device name: GPIOC */
#define BOARD_INITSNES_SNES_LAT_SIGNAL GPIO                        /*!<@brief GPIOC signal: GPIO */
#define BOARD_INITSNES_SNES_LAT_GPIO GPIOC                         /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITSNES_SNES_LAT_GPIO_PIN 9U                        /*!<@brief PORTC pin index: 9 */
#define BOARD_INITSNES_SNES_LAT_PORT PORTC                         /*!<@brief PORT device name: PORTC */
#define BOARD_INITSNES_SNES_LAT_PIN 9U                             /*!<@brief PORTC pin index: 9 */
#define BOARD_INITSNES_SNES_LAT_CHANNEL 9                          /*!<@brief GPIOC GPIO channel: 9 */
#define BOARD_INITSNES_SNES_LAT_PIN_NAME PTC9                      /*!<@brief Pin name */
#define BOARD_INITSNES_SNES_LAT_LABEL "J1[16]/D7"                  /*!<@brief Label */
#define BOARD_INITSNES_SNES_LAT_NAME "SNES_LAT"                    /*!<@brief Identifier name */
#define BOARD_INITSNES_SNES_LAT_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                                   /* @} */

/*! @name PORTA13 (number 43), J2[2]/D8
  @{ */
#define BOARD_INITSNES_SNES_DATA_PERIPHERAL GPIOA                  /*!<@brief Device name: GPIOA */
#define BOARD_INITSNES_SNES_DATA_SIGNAL GPIO                       /*!<@brief GPIOA signal: GPIO */
#define BOARD_INITSNES_SNES_DATA_GPIO GPIOA                        /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITSNES_SNES_DATA_GPIO_PIN 13U                      /*!<@brief PORTA pin index: 13 */
#define BOARD_INITSNES_SNES_DATA_PORT PORTA                        /*!<@brief PORT device name: PORTA */
#define BOARD_INITSNES_SNES_DATA_PIN 13U                           /*!<@brief PORTA pin index: 13 */
#define BOARD_INITSNES_SNES_DATA_CHANNEL 13                        /*!<@brief GPIOA GPIO channel: 13 */
#define BOARD_INITSNES_SNES_DATA_PIN_NAME PTA13                    /*!<@brief Pin name */
#define BOARD_INITSNES_SNES_DATA_LABEL "J2[2]/D8"                  /*!<@brief Label */
#define BOARD_INITSNES_SNES_DATA_NAME "SNES_DATA"                  /*!<@brief Identifier name */
#define BOARD_INITSNES_SNES_DATA_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                                   /* @} */

/*!
 * @brief Config pins for SNES controller
 *
 */
void BOARD_InitSnes(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
